# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter clover jasmine_sprout jason lavender platina tulip wayne whyred,$(TARGET_DEVICE)),)

endif
